# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmio.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmio(object):
    def setupUi(self, frmio):
        frmio.setObjectName("frmio")
        frmio.resize(291, 299)
        self.groupBox = QtWidgets.QGroupBox(frmio)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 271, 281))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.btnentrada = QtWidgets.QPushButton(self.groupBox)
        self.btnentrada.setGeometry(QtCore.QRect(10, 10, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnentrada.setFont(font)
        self.btnentrada.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnentrada.setObjectName("btnentrada")
        self.btnsaida = QtWidgets.QPushButton(self.groupBox)
        self.btnsaida.setGeometry(QtCore.QRect(10, 100, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnsaida.setFont(font)
        self.btnsaida.setObjectName("btnsaida")
        self.btnlista = QtWidgets.QPushButton(self.groupBox)
        self.btnlista.setGeometry(QtCore.QRect(10, 190, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnlista.setFont(font)
        self.btnlista.setObjectName("btnlista")

        self.retranslateUi(frmio)
        QtCore.QMetaObject.connectSlotsByName(frmio)

    def retranslateUi(self, frmio):
        _translate = QtCore.QCoreApplication.translate
        frmio.setWindowTitle(_translate("frmio", "Cadastro de Entrada/Saída"))
        self.btnentrada.setText(_translate("frmio", "Cadastro de Entrada"))
        self.btnsaida.setText(_translate("frmio", "Cadastro de Serviço"))
        self.btnlista.setText(_translate("frmio", "Lista de Serviços"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmio = QtWidgets.QDialog()
    ui = Ui_frmio()
    ui.setupUi(frmio)
    frmio.show()
    sys.exit(app.exec_())
