# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmitems.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmitems(object):
    def setupUi(self, frmitems):
        frmitems.setObjectName("frmitems")
        frmitems.resize(291, 389)
        self.groupBox = QtWidgets.QGroupBox(frmitems)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 271, 371))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.btnmarca = QtWidgets.QPushButton(self.groupBox)
        self.btnmarca.setGeometry(QtCore.QRect(10, 10, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnmarca.setFont(font)
        self.btnmarca.setObjectName("btnmarca")
        self.btnmedida = QtWidgets.QPushButton(self.groupBox)
        self.btnmedida.setGeometry(QtCore.QRect(10, 100, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnmedida.setFont(font)
        self.btnmedida.setObjectName("btnmedida")
        self.btnproduto = QtWidgets.QPushButton(self.groupBox)
        self.btnproduto.setGeometry(QtCore.QRect(10, 190, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnproduto.setFont(font)
        self.btnproduto.setObjectName("btnproduto")
        self.btnequip = QtWidgets.QPushButton(self.groupBox)
        self.btnequip.setGeometry(QtCore.QRect(10, 280, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnequip.setFont(font)
        self.btnequip.setObjectName("btnequip")

        self.retranslateUi(frmitems)
        QtCore.QMetaObject.connectSlotsByName(frmitems)

    def retranslateUi(self, frmitems):
        _translate = QtCore.QCoreApplication.translate
        frmitems.setWindowTitle(_translate("frmitems", "Cadastro de Items"))
        self.btnmarca.setText(_translate("frmitems", "Cadastro de Marcas"))
        self.btnmedida.setText(_translate("frmitems", "Cadastro de Medidas"))
        self.btnproduto.setText(_translate("frmitems", "Cadastro de Produtos"))
        self.btnequip.setText(_translate("frmitems", "Cadastro de Equipamentos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmitems = QtWidgets.QDialog()
    ui = Ui_frmitems()
    ui.setupUi(frmitems)
    frmitems.show()
    sys.exit(app.exec_())
