# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmmenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmmenu(object):
    def setupUi(self, frmmenu):
        frmmenu.setObjectName("frmmenu")
        frmmenu.resize(291, 300)
        self.groupBox = QtWidgets.QGroupBox(frmmenu)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 271, 281))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.btnpessoas = QtWidgets.QPushButton(self.groupBox)
        self.btnpessoas.setGeometry(QtCore.QRect(10, 10, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnpessoas.setFont(font)
        self.btnpessoas.setObjectName("btnpessoas")
        self.btnitems = QtWidgets.QPushButton(self.groupBox)
        self.btnitems.setGeometry(QtCore.QRect(10, 100, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnitems.setFont(font)
        self.btnitems.setObjectName("btnitems")
        self.btnio = QtWidgets.QPushButton(self.groupBox)
        self.btnio.setGeometry(QtCore.QRect(10, 190, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnio.setFont(font)
        self.btnio.setObjectName("btnio")

        self.retranslateUi(frmmenu)
        QtCore.QMetaObject.connectSlotsByName(frmmenu)

    def retranslateUi(self, frmmenu):
        _translate = QtCore.QCoreApplication.translate
        frmmenu.setWindowTitle(_translate("frmmenu", "Menu Principal"))
        self.btnpessoas.setText(_translate("frmmenu", "Cadastro de Pessoas"))
        self.btnitems.setText(_translate("frmmenu", "Cadastro de Items"))
        self.btnio.setText(_translate("frmmenu", "Cadastro de Entrada/Saída"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmmenu = QtWidgets.QDialog()
    ui = Ui_frmmenu()
    ui.setupUi(frmmenu)
    frmmenu.show()
    sys.exit(app.exec_())
